import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppSideBar from "@/components/ui/AppSideBar";
import AppNavBar from "@/components/ui/AppNavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex gap-2">

        <AppSideBar />
        <main className="w-screen border-green-600 border-4">

        <AppNavBar />
        <div className="p-4 h-screen border-orange-700 border-4">

        {children}
        </div>
        </main>
        </div>
      </body>
    </html>
  );
}
