import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppSideBar from "@/components/ui/AppSideBar";
import AppNavBar from "@/components/ui/AppNavBar";
import { ThemeProvider } from "@/components/providers/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        > 

        <div className="flex gap-2">

        <AppSideBar />
        <main className="w-screen border-4 border-blue-600 ">

        <AppNavBar />
        <div className="p-4 h-screen border-4
 border-orange-700 ">

        {children}
        </div>
        </main>
        </div>
   </ThemeProvider>
      </body>
    </html>
  );
}
